# Generated by Django 2.1.1 on 2019-03-13 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('userlogid', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=150)),
                ('topic', models.CharField(max_length=150)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
